
public enum QueryCommandsEnum
{
    GET_ANGLE_RECOMMENDATION,
    GET_ROAD_EDGE_DISTANCES,
    GET_ROAD_EDGE_DISTANCES_CHOOSE_VERTICALLY_CLOSEST_LEFT_RIGHT,
    IS_OFF_ROAD,
    GET_ROAD_EDGE_LIST,
}